---
#
# assumes common_play.yml already applied to all involved inventory
#
# because using elb, decided that extra-ebs not needed
# also, order matters:
#   1. playremote_play.yml
#   2. socializeremotely_play.yml
#

- hosts: '{{ target_hosts | default("tag_service_socializeremotely", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  vars:
    local_users:
      - name: dpmccabe
        groups: ['sudo']
        authorized:
          - https://github.com/dpmccabe.keys
      - name: '{{ service_name }}'
        groups: ['{{ hxjwt_shared }}']
        authorized: []

  vars_files:
    - vars/common_vars.yml
    - vars/playremote_vars.yml

  tasks:
    - include_role:
        name: external/nmaekawa.apt
      vars:
        apt_other_packages: "{{ apt_required_packages_playremote }}"

    - name: create shared group for playremote and socializeremotely
      group:
        name: "{{ hxjwt_shared }}"

    - include_role:
        name: external/Stouts.users
      vars:
        users_users: '{{ local_users }}'

    - name: create hxjwt shared dir
      file:
        path: '{{ hxjwt_shared_dir }}'
        owner: '{{ service_user }}'
        group: '{{ hxjwt_shared }}'
        mode: '0770'
        state: directory

    - name: query system for shared secret file
      stat:
        path: '{{ hxjwt_shared_private_path }}'
      register: shared_result

    - name: create hxjwt shared secret
      shell: '/usr/bin/uuidgen > {{ hxjwt_shared_private_path }}'
      when: not shared_result.failed and not shared_result.stat.exists

    - name: set permissions for hxjwt shared secret
      file:
        path: '{{ hxjwt_shared_private_path }}'
        owner: '{{ service_user }}'
        group: '{{ hxjwt_shared }}'
        mode: '0660'


- hosts: '{{ target_hosts | default("tag_service_socializeremotely", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  vars_files:
    - vars/common_vars.yml
    - vars/playremote_vars.yml
  handlers:
    - include_tasks: handlers/main.yml

  tasks:
    - name: read shared secret
      shell: 'cat {{ hxjwt_shared_private_path }}'
      register: shared_secret_result

    - debug:
        var: shared_secret_result

    - name: set shared secret in var
      set_fact:
          hxjwt_shared_secret: "{{ shared_secret_result.stdout }}"

    - name: install webapp
      include_role:
        name: webapp_install

    - name: run migration and collectstatic
      include_tasks: 'roles/webapp_install/tasks/django_manage.yml'

    - name: create django admin user
      include_tasks: 'roles/webapp_install/tasks/django_admin_user.yml'

    - name: restart django after collectstatic
      command: '/usr/bin/supervisorctl restart {{ service_name }}'

    - name: config nginx
      include_role:
        name: nginx
      vars:
        nginx_template_path: roles/nginx/templates/nginx_playremote.j2


  # install log/metrics scripts, syslog to s3, put-metrics to cloudwatch
- import_playbook: cloudwatch_scripts_play.yml
  when: ec2_tag_cluster == 'prod'

- import_playbook: nginx_backup_play.yml
  when: ec2_tag_cluster == 'prod'

  #- import_playbook: route53_play.yml
  when: "ec2_tag_cluster not in ['prod', 'demo', 'vagrant']"



