---

- name: Set the packagecloud repository name based on the version.
  set_fact:
      varnish_packagecloud_repo: "varnish{{ varnish_version|replace('.', '') }}"

- name: Ensure APT HTTPS Transport is installed.
  apt:
      name: apt-transport-https
      state: present

- name: Add packagecloud.io Varnish apt key.
  apt_key:
      url: https://packagecloud.io/varnishcache/{{ varnish_packagecloud_repo }}/gpgkey
      state: present

- name: Add packagecloud.io Varnish apt repository.
  apt_repository:
      repo: "deb https://packagecloud.io/varnishcache/{{ varnish_packagecloud_repo }}/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main"
      state: present

- name: Ensure Varnish is installed.
  apt:
      name: "{{ varnish_package_name }}"
      state: present


