---
    - name: create loris dirs
      file:
          path: '{{ item }}'
          owner: '{{ service_user }}'
          group: '{{ service_group }}'
          state: directory
      with_items: '{{ service_dirs_to_create }}'

    - include_tasks: roles/hx.loris/tasks/install_loris.yml
    - include_tasks: roles/hx.loris/tasks/setup_gunicorn.yml

    - name: restart service
      supervisorctl:
          name: '{{ service_name }}'
          state: restarted

